# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15iTIjCdSgCKqYN7L8IXkwGcYg_RqZOFz
"""

import pandas as pd

# 1. EXTRACT
data = {
    'Nome': ['Renato', 'Ana', 'Carlos'],
    'Conta': ['1001', '1002', '1003'],
    'Cartao': ['Visa', 'Master', 'Amex']
}
df = pd.DataFrame(data)

# 2. TRANSFORM
df['Mensagem'] = df['Nome'] + ", oferta especial no seu cartão " + df['Cartao']

# 3. LOAD
df.to_csv('resultado_santander.csv', index=False)
print("Pipeline executado com sucesso!")
print(df)